# Generated by Django 3.2.3 on 2021-06-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internship_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
