# Generated by Django 3.2.3 on 2021-05-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assigned_to',
            field=models.CharField(choices=[('Rekha', 'Rekha'), ('test', 'test')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.CharField(choices=[('Developer', 'Developer'), ('AI', 'AI')], max_length=100),
        ),
    ]
