# Generated by Django 3.2.3 on 2021-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='completion_letter_issue_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='offer_letter_issue_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
