# Generated by Django 3.2.3 on 2021-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210531_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enable_offer_letter_download',
            field=models.BooleanField(default=False, verbose_name='enable_offer_letter_download'),
        ),
        migrations.AddField(
            model_name='student',
            name='request_for_offer_letter',
            field=models.BooleanField(default=False, verbose_name='request_for_offer_letter'),
        ),
    ]
