# Generated by Django 3.2.3 on 2021-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210603_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duration',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('6', '6')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
