# Generated by Django 3.2.3 on 2021-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_student_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enable_completion_letter_download',
            field=models.BooleanField(default=False, verbose_name='enable_completion_letter_download'),
        ),
        migrations.AddField(
            model_name='student',
            name='enable_completion_letter_download_urgent',
            field=models.BooleanField(default=False, verbose_name='enable_completion_letter_download_urgent'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='no_of_absents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='request_for_completion_letter',
            field=models.BooleanField(default=False, verbose_name='request_for_completion_letter'),
        ),
        migrations.AddField(
            model_name='student',
            name='status_of_project',
            field=models.CharField(choices=[('Incomplete', 'INCOMPLETE'), ('Partially Completed', 'PARTIALLY COMPLETED'), ('Completed', 'COMPLETED')], default='Incomplete', max_length=100),
        ),
    ]
