# Generated by Django 3.2.3 on 2021-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210603_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='duration',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('4', '4'), ('6', '6')], max_length=2),
        ),
    ]
